' 可以粘贴到在线 PlantUML 去编辑 https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa700002
' 或者 VS Code 插件 PlantUML 插件 (jebbs.plantuml) 来编辑
@startuml webrtc-connection

title WebRTC 音视频通话流程

actor 用户1 as user1
actor 用户2 as user2
participant 信令服务器 as signaling

note left of user1 : 初始化本地媒体流\n设置 candidate 回调

user1 -> signaling : 创建房间 (join)
signaling --> user1 : 创建成功 (created)

user1 -> signaling : 邀请 (invite)
signaling --> user2 : 转发邀请 (invite)

user2 -> signaling : 加入房间 (join)
signaling --> user2 : 加入成功 (joined)

note left of user2 : 初始化本地媒体流\n设置 candidate 回调

signaling --> user1 : 有人进入房间 (peer-joined)

note left of user1 : 创建 Offer \n保存 offer (setLocalDescription)

user1 -> signaling : 发送 Offer (offer)
signaling --> user2 : 转发 Offer (offer)

note left of user2 :  保存 Offer (setRemoteDescription)\n创建 Anwser \n保存 Anwser (setLocalDescription)

user2 -> signaling : 发送 Answer (answer)
signaling --> user1 : 转发 Answer (answer)

note left of user1 :  保存 Anwser (setRemoteDescription)

user1 -> signaling : 发送 ICE Candidate (candidate)
signaling --> user2 : 转发 ICE Candidate (candidate)
note left of user2 : 处理远程媒体流

user2 -> user1 : 发送 ICE Candidate (candidate)
note left of user1 : 处理远程媒体流

user1 <[#00e300]-> user2 : 接收对方媒体流，开始音视频通话

user1 -[#f00000]> signaling : 挂断 (hungup)
note left of user1 : 关闭本地媒体流、关闭 peer 连接
signaling -[#f00000]-> user2 : 转发挂断 (hungup) 或者对端意外连接断开 (peer-leave)
note left of user2 : 关闭本地媒体流、关闭 peer 连接

@enduml
